site_name: èƒ¡æ¡ƒé…±ä½¿ç”¨æŒ‡å—
site_description: è¿™æ˜¯ä¸€ä»½ä¸“å±çš„ã€ŒğŸ“–èƒ¡æ¡ƒé…±ä½¿ç”¨è¯´æ˜ä¹¦ã€ï¼Œä¹Ÿæ˜¯ä¸€åº§æ‰¿è½½ä¸ªäººå°ä¸–ç•Œçš„æ•°å­—å±•é¦†ã€‚åœ¨è¿™é‡Œï¼Œä½ ä¸ä»…èƒ½è§£é”æˆ‘çš„æˆé•¿è½¨è¿¹ã€ç”Ÿæ´»ç¢ç‰‡ä¸å°ä¼—çˆ±å¥½ï¼Œè¿˜èƒ½è·å–ä¸æˆ‘ç•…å¿«èŠå¤©çš„ã€ŒğŸ§­å…³é”®è¯æŒ‡å—ã€ã€å‘ç°éšè—å½©è›‹çš„ã€ŒğŸ—ºï¸å¯»å®åœ°å›¾ã€ã€‚
site_author: Hutao_zyf
site_url: https://midori.fun/aboutme
use_directory_urls: false  
theme:
  name: material
copyright: Copyright &copy; Hutao_zyf | ç”±<a href="https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral">åˆæ‹äº‘</a>æä¾›äº‘å­˜å‚¨æœåŠ¡ | licensed under <a href="https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1">CC BY 4.0</a>
nav:
  - index.md
  - ğŸ“ æ ¸å¿ƒæ¡£æ¡ˆé¦†:
    - æ ¸å¿ƒæ¡£æ¡ˆ: Core/CoreData.md
    - è”ç³»æ–¹å¼: Core/Contacts.md 
  - ğŸ“š ç”Ÿæ´»æ‰©å±•åŒ…:
    - å…´è¶£å›¾è°±: Plugins/hb.md
    - ç¥æ•™ç±»:
      - GNU_Linux: Plugins/btw/GNU_Linux.md
      - ç”µå­éŸ³ä¹: Plugins/btw/elec.md
      - è¿½ç•ªåˆ—è¡¨: Plugins/btw/anime.md
    - äºšæ–‡åŒ–:
      - æ ¸ç±»ç¾å­¦/Y2K: Plugins/cu/y2k.html
  - ğŸ’¬ èŠå¤©æ¥å£åº“:
    - å¯¹è¯åè®®: API/tkapi.md
  - â“ Q&A:
    - å¸¸è§é—®é¢˜: qa/qa.md
  - ğŸ“ Blog:
    - ã‚²ãƒ¼ãƒ é–‹ç™ºéƒ¨: /


markdown_extensions:
  - extensions.spoiler_extension
  - extensions.remark_extension
  - extensions.pinyin_extension
  
extra_css:
  - https://114514.zroevn.cn/imgs/spoiler.css
  - https://114514.zroevn.cn/imgs/remark.css
  - https://114514.zroevn.cn/imgs/pinyin.css

plugins:
  - search:
      lang:
        - zh
        - en
  - macros



